
name: Deploy sub data folders for rewards and evmallowance

on:
  workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p public/data
    - run: echo hello > public/data/text.txt
    - uses: actions/upload-artifact@v4
      with:
        name: my-file
        path: public/data/text.txt
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-file
          path: data
